# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 09:36
from __future__ import unicode_literals

import apps.instalaciones.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaDisponibleInstalacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(1, b'Lunes'), (2, b'Martes'), (3, b'Miercoles'), (4, b'Jueves'), (5, b'Viernes'), (6, b'Sabado'), (7, b'Domingo')])),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('disponible', models.BooleanField(default=1)),
                ('disponible_todo_el_dia', models.BooleanField(default=1)),
                ('fecha_creacion', models.DateTimeField(editable=False)),
                ('fecha_modificacion', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', sorl.thumbnail.fields.ImageField(blank=True, upload_to=apps.instalaciones.models.path_and_rename)),
                ('nombre', models.CharField(max_length=450)),
                ('descripcion', models.TextField()),
                ('reglamento', models.TextField()),
                ('activo', models.BooleanField(default=1)),
                ('fecha_creacion', models.DateTimeField(editable=False)),
                ('fecha_modificacion', models.DateTimeField(editable=False)),
                ('usuario_creo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservacionInstalacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reservacion', models.DateTimeField()),
                ('hora_empieza', models.TimeField()),
                ('hora_termina', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(editable=False)),
                ('fecha_modificacion', models.DateTimeField(editable=False)),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.Instalacion')),
                ('usuario_creo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='diadisponibleinstalacion',
            name='instalacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instalaciones.Instalacion'),
        ),
    ]
